name: options-saas
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - greenlet=3.3.0
  - icu=78.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=19.1.7
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - ncurses=6.5
  - numpy=2.4.0
  - openssl=3.6.0
  - pandas=2.3.3
  - pip=25.3
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlalchemy=2.0.45
  - tk=8.6.13
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - alembic==1.17.2
      - anyio==4.12.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.14.3
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - curl-cffi==0.10.0
      - dnspython==2.8.0
      - dotenv==0.9.9
      - ecdsa==0.19.1
      - email-validator==2.3.0
      - fastapi==0.95.2
      - frozendict==2.4.7
      - h11==0.16.0
      - idna==3.11
      - jsonformatter==0.3.4
      - mako==1.3.10
      - markupsafe==3.0.3
      - multitasking==0.0.12
      - passlib==1.7.4
      - peewee==3.18.3
      - platformdirs==4.5.1
      - prometheus-client==0.23.1
      - protobuf==5.29.5
      - psycopg==3.3.2
      - psycopg-binary==3.3.2
      - pyasn1==0.6.1
      - pycparser==2.23
      - pydantic==1.10.7
      - python-dotenv==1.0.0
      - python-jose==3.5.0
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - requests==2.32.5
      - rsa==4.9.1
      - sentry-sdk==2.48.0
      - soupsieve==2.8
      - starlette==0.27.0
      - urllib3==2.6.0
      - uvicorn==0.22.0
      - websockets==15.0.1
      - yfinance==0.2.59
